@baseUrl = http://localhost:3000/api/candidates


### Get all candidates
GET {{baseUrl}}


###
GET {{baseUrl}}/56ec85e6-7243-455b-8ebd-6a3c7114f23c


### Create candidate
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="userId"

8ad9db84-4289-4d0a-af9e-21856c869bf3
------WebKitFormBoundary123456
Content-Disposition: form-data; name="partyId"

dfeccadc-80d0-44a2-8356-72918f1930c1
------WebKitFormBoundary123456
Content-Disposition: form-data; name="slogan"

ביחד נבנה עתיד טוב יותר
------WebKitFormBoundary123456
Content-Disposition: form-data; name="description"

אני פועל למען חברה טובה יותר, שוויונית וחזקה.
------WebKitFormBoundary123456
Content-Disposition: form-data; name="candidateImage"; filename="DSC_2402.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\websizephotos\צלם 2\DSC_2402.jpg
------WebKitFormBoundary123456
Content-Disposition: form-data; name="candidatePlatform"; filename="sample-document.pdf"
Content-Type: application/pdf

< C:\Users\USER\Desktop\sample-document.pdf
------WebKitFormBoundary123456--


### Update candidate - text only


### Update candidate - text only
PATCH {{baseUrl}}/56ec85e6-7243-455b-8ebd-6a3c7114f23c
Content-Type: application/json

{
  "slogan": "סיסמה מעודכנת"
}


### Update candidate - image


### Update candidate - image
PATCH {{baseUrl}}/56ec85e6-7243-455b-8ebd-6a3c7114f23c
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="candidateImage"; filename="DSC_2402.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\websizephotos\צלם 2\DSC_2402.jpg
------WebKitFormBoundary123456--


### Update candidate - new image
PATCH {{baseUrl}}/56ec85e6-7243-455b-8ebd-6a3c7114f23c
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="candidateImage"; filename="DSC_2402.jpg"
Content-Type: image/jpeg

< C:\Users\USER\Downloads\websizephotos\צלם 2\DSC_2402.jpg
------WebKitFormBoundary123456--


### Update candidate - new PDF
PATCH {{baseUrl}}/56ec85e6-7243-455b-8ebd-6a3c7114f23c
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary123456

------WebKitFormBoundary123456
Content-Disposition: form-data; name="candidatePlatform"; filename="sample-document.pdf"
Content-Type: application/pdf

< C:\Users\USER\Desktop\sample-document.pdf
------WebKitFormBoundary123456--