@baseUrl = http://localhost:3000/api/parties


### Get all parties
GET {{baseUrl}}


### Get party by id
GET {{baseUrl}}/9a796493-e01e-4b63-9970-9ce40cb97bdf


### Create party - Admin
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "מפלגת החברה הטובים",
  "slogan": "ביחד בונים חברה טובה יותר",
  "description": "מפלגת החברה הטובים פועלת למען חברה צודקת, שוויונית וחזקה יותר."
}


### Update party - Admin
PATCH {{baseUrl}}/9a796493-e01e-4b63-9970-9ce40cb97bdf
Content-Type: application/json

{
  "slogan": "ביחד בונים עתיד טוב יותר"
}


### Delete party - Admin
DELETE {{baseUrl}}/9a796493-e01e-4b63-9970-9ce40cb97bdf